### ISSUE TITLE
прив линк. 

### ISSUE THREAD

**Issue by FunnyRain** [DanilZz/VkCoreChatBot#2]
иссуе вообщем такой: 

хуй
хуй
хуй
хуй
и
ещё
раз
ХУХХУХУХУХУХУХЙ
ХУЙ
ХУЙ
_ХУЙ_ 
**ХУЙ** 
~~НЕ ХУЙ~~ ХУЙ

**Comment by An0ther1337** [comment]
# согл

**Comment by FunnyRain** [comment]
@An0ther1337 **соси, чмарк**

**Comment by DanilZz** [comment]
сог
